# Unit 2 task

**Updated 2023-10-09**

This Jupyter notebook is a template for this week's assignment. You should fill in the blank code and text cells below to answer the questions, and upload your completed notebook to Moodle for marking.

Remember to:
* print out the results of each calculation;
* where you are asked to complete text cells, make sure you use complete, grammatically correct sentences.

Make sure you run the cell below to import the NumPy package.

In [1]:
import numpy as np

## Part 1

### (a)

The following statement creates an array of evenly spaced values:

    np.array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

Use an appropriate NumPy function in the next cell to create an array containing the same values in a more efficient way, and assign this to a variable called `array_a`.

In [2]:
### STUDENT CODE CELL
array_a = np.linspace(0.5, 3.0, 6)
print(array_a)

[0.5 1.  1.5 2.  2.5 3. ]


### (b)

The following statement creates an array of evenly spaced **integers**: 

    array([ 5, 10, 15, 20, 25, 30])

Again, use an appropriate NumPy function in the next cell to create an array containing the same values in a more efficient way, and assign this to a variable called `array_b`.

In [3]:
### STUDENT CODE CELL
array_b = np.linspace(5, 30, 6, dtype=int)
print(array_b)

[ 5 10 15 20 25 30]


### (c)

Multiply the values in `array_a` and `array_b` together, assigning the results to a variable `array_c`.

In [4]:
### STUDENT CODE CELL
array_c = array_a * array_b
print(array_c)

[ 2.5 10.  22.5 40.  62.5 90. ]


### (d)

Use array slicing to create an array `array_d` containing the elements from `array_c` but omitting the first and last elements.

In [5]:
### STUDENT CODE CELL
array_d = array_c[1:5]
print(array_d)

[10.  22.5 40.  62.5]


### (e)

Use your web searching skills to find NumPy functions that will calculate the dot product and the cross product of two vectors. Use these functions to calculate both products for the vectors (0.3, 0.4, 1.2) and (0.4, -0.3, 1.2).

In [6]:
### STUDENT CODE CELL
vector_a = [0.3, 0.4, 1.2]
vector_b = [0.4, -0.3, 1.2]

dot = np.dot(vector_a, vector_b)
cross = np.cross(vector_a, vector_b)

print(f"dot: {dot}, cross: {cross}")

dot: 1.44, cross: [ 0.84  0.12 -0.25]


### (f)

The first few storm names chosen by the UK Met Office for 2023-24 are given in this list:

In [7]:
storms = ["Agnes","Babet","Ciarán","Debi","Elin","Fergus","Gerrit"]

Use a for loop to print each name on a separate line, prefixed by the word "Storm", i.e.

    Storm Agnes
    Storm Babet
    
and so on.

In [8]:
### STUDENT CODE CELL
for name in storms:
    print(f"Storm {name}")

Storm Agnes
Storm Babet
Storm Ciarán
Storm Debi
Storm Elin
Storm Fergus
Storm Gerrit


### (g)

The for loop is useful when you need to deal with each element of an array in turn, but it can be slow compared to more specialized NumPy functions. In two separate code cells below, you should try adding together the contents of the same array `data` in two different ways: 
- using a loop;
- using the function `np.sum`.

The `%%time` function (a Jupyter "magic" function, not part of Python) will tell you how long each takes. You may need to adjust the size of the array to get useful results.

Use the following text cell to comment on the results.

In [9]:
# Generate some (pseudo)random numbers as input for the next tasks.
#
# Depending on the speed of your computer, you may want to vary the size of this array.
# Remember that you can interrupt the kernel if a calculation is taking too long!  
data = np.random.random(size=10000)

# np.sum function is faster than using a for loop
# avg time: 0.18 ms vs 1.60 ms (~ 10x faster)

In [10]:
%%time
### STUDENT CODE CELL

sum = 0.
# Add a loop here to add each element of data in turn to "sum".
for n in data:
    sum += n

print(f"The sum is {sum}")

The sum is 5021.1240819745835
CPU times: total: 0 ns
Wall time: 1.04 ms


In [11]:
%%time
### STUDENT CODE CELL

sum = np.sum(data) # Replace this line with a call to the np.sum function.

print(f"The sum is {sum}")

The sum is 5021.124081974585
CPU times: total: 0 ns
Wall time: 1.45 ms


##### STUDENT TEXT CELL: add to this text cell to comment on the results of timing the two different ways of carrying out the same calculation.

## Part 2

In unit 1 you were asked to calculate the value of the fourth-order Legendre polynomial for a given value of x:

$$
f(x) = \frac{1}{8} \left( 35 x^4 - 30 x^2 + 3 \right)
$$

### (a)

You should now define a function that can calculate the corresponding value of this polynomial for any value of x, or an array of x values.

In [12]:
### STUDENT CODE CELL
def f(x):
    """
    Fourth-order Legendre polynomial function.

    Parameters:
    x (int, float): Input value.

    Returns:
    float: Value of the fourth-order Legendre polynomial at x.
    """
    return( (1/8) * ( (35*(x**4)) - (30*(x**2)) + (3) ) )

### (b)

Use your function to print (with appropriate text) the value of the polynomial at $x=0.123$.

In [13]:
### STUDENT CODE CELL
print(f"f(0.123) = {f(0.123)}")

f(0.123) = 0.319267629054375


### (c)

Use your function, and a suitable array, to print the value of the polynomial at $x = 0, 0.1, 0.2 \ldots 1$.

In [14]:
### STUDENT CODE CELL
array_x = np.linspace(0, 1, 11)

for i in array_x:
    print(f"f({i:.1f}) = {f(i):.7f}")

### Alternative

print(f(array_x))

f(0.0) = 0.3750000
f(0.1) = 0.3379375
f(0.2) = 0.2320000
f(0.3) = 0.0729375
f(0.4) = -0.1130000
f(0.5) = -0.2890625
f(0.6) = -0.4080000
f(0.7) = -0.4120625
f(0.8) = -0.2330000
f(0.9) = 0.2079375
f(1.0) = 1.0000000
[ 0.375      0.3379375  0.232      0.0729375 -0.113     -0.2890625
 -0.408     -0.4120625 -0.233      0.2079375  1.       ]
